version: '3'
services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    ports:
      - 5432:5432
    restart: unless-stopped
  java-user-service:
    image: docker.io/artsyom88/spring-boot-user-manager:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres_db
  java-place-service:
    image: docker.io/artsyom88/spring-boot-place-manager:0.0.1-SNAPSHOT
    ports:
       - 8081:8080
    restart: always
    depends_on:
      - postgres_db